evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload


plug "andreyorst/fzf.kak"
map global normal <c-p> ": fzf-mode<ret>"

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option buffer indentwidth 4
    set-option global softtabstop 4
} config %{
    hook global WinSetOption .* expandtab
}

plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}


plug "occivink/kakoune-snippets" %{
    source "%val{config}/snippets.kak"
}

add-highlighter global/ number-lines -relative

map global user n :bn<ret>
map global user p :bp<ret>

