theme = "everforest_dark"

[editor]
line-number = "relative"
bufferline = "always"
true-color = true
color-modes = true
end-of-line-diagnostics = "hint"
indent-heuristic = "tree-sitter"


[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"


[editor.soft-wrap]
enable = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"
newline = "none"


[keys.normal]
C-c = ":buffer-close"
C-x = ":write-quit"


# Yazi picker with zellij
# https://yazi-rs.github.io/docs/tips/#helix-with-zellij
C-y = ":sh zellij run -n 'Yazi' -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"


o = ["open_below", "normal_mode"]
O = ["open_above", "normal_mode"]

"$" = "goto_line_end"
"_" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
S = "surround_add"


esc = ["collapse_selection", "keep_primary_selection"]

j = "move_line_down"
k = "move_line_up"

C-e = ":pipe ~/.config/helix/bin/emmet.py"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
"$" = "goto_line_end"
G = "goto_file_end"
"%" = "match_brackets"
S = "surround_add"
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
