[language-server.v-analyzer]
command = "/home/aino/.local/bin/v-analyzer/bin/v-analyzer"
args = [ "--stdio" ]

[[language]]
name = "v"
roots = [ "v.mod" ]
file-types = ["v", "vv"]
language-servers = [ "v-analyzer" ]

[[language]]
name = "verilog"
file-types = ["vh", "sv", "svh"]

[language-server.ruby-lsp]
command = "bundle"
args = ["exec", "ruby-lsp"]
config = { diagnostics = true, formatting = true }

[[language]]
name = "ruby"
roots = ["Gemfile"]
file-types = [
  "rb",
  "rake",
  "irb",
  "gemspec",
  "rabl",
  "jbuilder",
  "jb",
  "podspec",
  "rjs",
  "rbi",
  "rbs",
  { glob = "rakefile" },
  { glob = "gemfile" },
  { glob = "Rakefile" },
  { glob = "Gemfile" },
  { glob = "Podfile" },
  { glob = "Vagrantfile" },
  { glob = "Brewfile" },
  { glob = "Guardfile" },
  { glob = "Capfile" },
  { glob = "Cheffile" },
  { glob = "Hobofile" },
  { glob = "Appraisals" },
  { glob = "Rantfile" },
  { glob = "Berksfile" },
  { glob = "Berksfile.lock" },
  { glob = "Thorfile" },
  { glob = "Puppetfile" },
  { glob = "Fastfile" },
  { glob = "Appfile" },
  { glob = "Deliverfile" },
  { glob = "Matchfile" },
  { glob = "Scanfile" },
  { glob = "Snapfile" },
  { glob = "Gymfile" },
]
language-servers = ["ruby-lsp"]
auto-format = true
